### ISSUE TITLE
US01 - CRUD de Conta

### ISSUE THREAD

**Issue by lipeaaraujo** [UnBArqDsw2024-2/2024.2_G7_Entrega_Entrega_03#12]
### Descrição

- **Como um(a)**: Usuário
- **Eu quero**: Criar, visualizar, editar e deletar minha conta
- **Para que eu possa**: Acessar as funcionalidades do sistema e ter controle sobre a conta

### Tarefas

- [x] CRUD do Usuário (backend)
- [x] Criar página de cadastro de usuário (frontend)

### Possíveis GoFs

- [ ] #2 (fazer a conexão com o banco)
- [x] #3 
- [ ] #5
- [ ] #8 
- [ ] #7 
- [ ] #6
- [ ] #9   

### Protótipo

![Image](https://github.com/user-attachments/assets/e784d61d-5be8-4f62-804b-655c48c93891)
![Image](https://github.com/user-attachments/assets/bf25e33f-eb06-42f2-b83a-20d2903c9dbb)

### Critérios de Validação

- [x] Dado que o aplicativo esteja aberto, quando estiver na tela de login, ele deve ser capaz de acessar a página de criação de conta e criar sua conta, então sua conta deve ser adicionada no sistema;
- [ ] Dado que o usuário esteja logado em sua conta, quando acessar seu perfil, ele deve ser capaz de editar os dados da conta, então os dados da conta deverão ser atualizados no sistema; (#16)
- [ ] Dado que o usuário esteja logado em sua conta, quando acessar seu perfil, ele deve ser capaz de deletar sua conta, então os dados da conta deverão ser apagados do sistema; (#16)
- [ ] Dado que o usuário esteja logado em sua conta, quando entrar no aplicativo, ele deve ser capaz de visualizar as informações da conta logada. (#16)

### Código de Conduta

- [x] Concordo em cumprir o Código de Conduta do projeto
